#! /bin/sh
pgrep -x dunst || dunst &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a black-back state=fullscreen 
bspc rule -a passwd state=floating rectangle=240x112+506+752
bspc rule -a cava_term state=floating desktop='^1' sticky=off border=on rectangle=696x93+575+699
bspc rule -a mpv state=floating
bspc rule -a tty_clock state=floating desktop="^1" rectangle=390x220+6+30


setxkbmap -option grp:alt_shift_toggle us,ru


#sxhkd &


~/.scripts/change-mode.sh
#alacritty

