#tabspaces = 4

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"

[mouse]

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[font]
size = 8.5

[font.bold]
family = "Iosevka Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka Nerd Font"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
#auto_scroll = false
#faux_multiplier = 3
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[window]
opacity = 0.4

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 8
y = 5

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]


[cursor]
# Set to false to disable completely
smooth_motion = true
# 0.0 = cursor is not moving, 1.0 = cursor moves instantly
smooth_motion_factor = 0.5
# 0.0 = broken, 1.0 = cursor shape is unaffected by movement
smooth_motion_spring = 0.5
# Limits how the cursor size may change
smooth_motion_max_stretch_x = 100.0
smooth_motion_max_stretch_y = 100.0
# Supposed to help with flickering in some TUIs, keep it low (`man alacritty.5`)
smooth_motion_antijitter_ms = 0
# Override "block" cursor if you don't like how it looks in this fork
block_replace_shape = "underline"


[seltools]
# `false` by default, naturally
enabled = true
# `true` by default, enables JSON parsing (the only thing seltools can do for now)
parse_json = true
# Text-based UI width
hint_width = 40
